"""empty message

Revision ID: 7f3ee4840c13
Revises: 52252ef41837
Create Date: 2024-01-20 18:47:33.027727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7f3ee4840c13"
down_revision = "52252ef41837"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_cart", schema=None) as batch_op:
        # batch_op.drop_constraint("FK_user_cart_order", type_="foreignkey")
        # batch_op.drop_column("order_id")
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_cart", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order_id", sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, "order", ["order_id"], ["id"])

    op.drop_table("order_item")
    # ### end Alembic commands ###
